name: dependalint

on:
  push:
    paths:
      - ".github/dependabot.yaml"
      - ".github/workflows/dependalint.yaml"
  pull_request:
    paths:
      - ".github/dependabot.yaml"
      - ".github/workflows/dependalint.yaml"

permissions:
  contents: read

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Check out repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Set up Go
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version-file: go.mod

      - name: run dependalint
        run: go run ./cmd/dependalint
